language: node_js
sudo: true
node_js: stable
script:
- npm test
env:
  global:
  - BX_APP=document-conversion-demo
  - BX_API=https://api.ng.bluemix.net
  - BX_ORGANIZATION=WatsonPlatformServices
  - BX_SPACE=demos
before_deploy: npm install -g https://github.com/andresfvilla/bx-blue-green
deploy:
  provider: script
  script:
  - bx-blue-green-travis
  on:
    repo: watson-developer-cloud/document-conversion-nodejs
    branch: master
  skip_cleanup: true
